# Setup
title:       	My Diary Has Equations In It 
tagline:      A blog about Silicon Valley, Computer Vision, politics, and feminism. 
baseurl:      ""
paginate:     1

# About/contact
author:
  name:      	Amy Bearman 
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
